version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=products_db
      - DB_PORT=3306
    command: ["sh", "-c", "npx sequelize-cli db:migrate && node dist/server.js"]

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=products_db
      - MYSQL_ROOT_PASSWORD=rootpassword  # ✅ Use only this
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  mysql_data:
